<img src="https://i2.wp.com/hackwagon.com/wp-content/uploads/2017/02/Logo-Web-Export.png?ssl=1" width=200/>

<h1> Hackwagon Academy - DS101 Lab 2 </h1>

This lab exercise consists of 10 questions, with each correct answer to be awarded 2 marks, totalling up to 20 marks.

Attempt but minor syntax errors are awarded half the mark.

In [ ]:
#Before you start, please perform the following 2 steps:
#1. Rename the file to <First_Name>_<Last_Name>_DS101_Lab_1 e.g. john_doe_DS101_Lab_1

#2. Fill in your details here:
#Name                    : Ng Ming Bing

#Start of Course Class(Edit accordingly): 22 Dec 2018 3.45pm-6.45pm

# FOR TA/INSTRUCTOR 
# Total Marks:  / 20

## Warm Up

### Question 1

Create a simple if-else algorithm to check if you're ready:

If `ready` = `True`, expected output:

    I am ready!
    
elif `ready` = `False`, expected output:

    I am not :/ 

In [3]:
ready = False
if ready == True :
    print('I am ready!')
elif ready == False :
    print('I am not :/')

I am ready!


### Question 2

Given the following 2 dictionaries, find the total number of views then create a <b>new dictionary</b> called `summary_data` and print the dictionary.

**Expected Output**:

    {
        'all_views': 104600
    }

In [19]:
baby_by_bieber = {
    'views': 5600
}

yellow_coldplay = {
    'views': 99000
}

all_views = baby_by_bieber['views'] + yellow_coldplay['views']

summary_data = {
    'all_views': all_views
}
print(summary_data)

{'all_views': 104600}


## YouTube Data Analyst

#### Context

Right now, you are a data analyst at YouTube. You're working with a team to answer some simple analytics questions. Due to some buggy code written previously by an intern, it is now your job to debug the mistakes. At the same time, some old data has made its way into the production environment, and it is within your job scope to filter out those as well.

The following cell shows a snippet of code that an intern has written previously, and the definitions for each of the key-value pairs are described as per below.

|Keys:| <center>`"title"` </center>       |<center> `"company"`</center> | <center> `"views"`</center>  | 
|:---| :----------- |:----------------- | :----- | 
|<b>Value:</b>| Title of the video ad  <br><br><center>e.g.</center><br><center>`"Title A"` </center>     | Company name <br><br><center>e.g.</center><br> <center>`"Company A"`</center> | Number of video views<br><br><center>e.g.</center><br><center> `1000`</center>|

<br>

<font color='red'><b>Remember to run the code snippet below with `CTRL-ENTER` or `SHIFT-ENTER` or `SHIFT-RETURN` by clicking the run button above to initialise the variables.</b></font>


In [30]:
video_ad_1 = {
    "title": "Healthy Living", 
    "company": "Health Promotion Board", 
    "views": 65423
}

video_ad_2 = {
    "title": "Get a ride, anytime anywhere", 
    "company": "GoJek", 
    "views": 54323
}

video_ad_3 = {
    "title": "Send money to your friends with GrabPay", 
    "company": "Grab", 
    "views": 654306
}

video_ad_4 = {
    "title": "GrabEat now delivers nationwide", 
    "company": "Grab", 
    "views": 5123
}

video_ad_5 = {
    "title": "Get cabs now with GoJekFlash", 
    "company": "GoJek", 
    "views": 62353
}

### Question 3

Find and print out the total views of all the videos provided above. You are to use index key method of the dictionaries to **extract** the data and aggregate total views. Make sure you **do not hard-code the answers**.

**Example of hard-coding:**
```python
# This is hard-coding, and should not be done
print(65423 + 54323 + 654306 + 5123 + 62353)
```

**Expected output:**
```python
841528
```

In [31]:
total_views = video_ad_1['views'] + video_ad_2['views'] + video_ad_3['views'] + video_ad_4['views'] + video_ad_5['views']
print(total_views)


841528


### Question 4

**A Company and Views Database doesn't exists. Create a NEW dictionary that stores the total views of videos for each unique company**, and print the dictionary. You are to use the key-value pair of the dictionaries to access the data, and to add up the total views.

Make sure you **do not hard-code the answers**

**Example of hard-coding:**
```python
# This is hard-coding, and should not be done
views_dict = {}
views_dict = {"Health Promotion Board": 65423, "GoJek": 54323 + 62353, "Grab": 654306 + 5123}
print(views_dict)
```
The above will give you the right answer, but that is not how we want you to do it. In the above method, if the data in the original dictionary is changed, that means we have to change our calculations. We want our method to be dynamic!


**Expected output:**
```python
{'Health Promotion Board': 65423, 'GoJek': 116676, 'Grab': 659429}
```

**Hint:**
```python
views_dict = {}
views_dict["GoJek"] = video_ad_2["views"] + ... + ...
print(views_dict)
```


In [32]:
views_dict = {}
views_dict["Health Promotion Board"] = video_ad_1["views"]
views_dict["GoJek"] = video_ad_2["views"] + video_ad_5["views"]
views_dict["Grab"] = video_ad_3["views"] + video_ad_4["views"]
print(views_dict)

{'Health Promotion Board': 65423, 'GoJek': 116676, 'Grab': 659429}


### Question 5

The following represents a <b>list of dictionaries</b>. Each dictionary represents a video advertisement and its respective view numbers. Unfortunately, these advertisements are more than a year old, and YouTube is not interested in performing analysis for these older videos.

Remove the 2 old videos from the variable `video_ads_list` by the use of the <b>`del`</b> function, and print the resulting `video_ads_list` variable.

Make sure you **do not hard-code the answers**

**Example of hard-coding:**
```python
# This is hard-coding, and should not be done
video_ads_list = []
print(video_ads_list)
```

**Expected output:**
```python
[]
```

In [33]:
video_ads_list = [
    {"title": "Get the newest iPhone 6", "company": "Apple", "views": 389824},
    {"title": "Samsung Galaxy S2 out now!", "company": "Saumsung", "views": 230123}
]

# write some code below to show us how you would clean out this list with the use of del function
del video_ads_list[:]
print(video_ads_list)

[]


### Question 6

After cleaning out the above `video_ads_list` list, now we want to add in the newer videos (variables declared in part 1) e.g. `video_ad_1`, `video_ad_2` etc...

Your task is to add all the newer videos into the variable `video_ads_list` by the use of the `.append()` function, and to print out the resulting `video_ads_list` variable. <b>Recall that you have already created 5 video_ads in the cells above. </b>

Make sure you **do not hard-code the answers**

**Example of hard-coding:**
```python
# This is hard-coding, and should not be done
video_ads_list = [
    {"title": "Healthy Living", "company": "Health Promotion Board", "views": 65423}, 
    {"title": "Get a ride, anytime anywhere", "company": "GoJek", "views": 54323}
]
print(video_ads_list)
```

**Expected output:**
```python
[
 {'title': 'Healthy Living', 'company': 'Health Promotion Board','views': 65423},
 {'title': 'Get a ride, anytime anywhere', 'company': 'GoJek', 'views': 54323},
 {'title': 'Send money to your friends with GrabPay', 'company': 'Grab', 'views': 654306},
 {'title': 'GrabEat now delivers nationwide', 'company': 'Grab', 'views': 5123},
 {'title': 'Get cabs now with GoJekFlash', 'company': 'GoJek', 'views': 62353}
]
```

In [34]:
video_ads_list.append(video_ad_1)
video_ads_list.append(video_ad_2)
video_ads_list.append(video_ad_3)
video_ads_list.append(video_ad_4)
video_ads_list.append(video_ad_5)
print(video_ads_list)

[{'title': 'Healthy Living', 'company': 'Health Promotion Board', 'views': 65423}, {'title': 'Get a ride, anytime anywhere', 'company': 'GoJek', 'views': 54323}, {'title': 'Send money to your friends with GrabPay', 'company': 'Grab', 'views': 654306}, {'title': 'GrabEat now delivers nationwide', 'company': 'Grab', 'views': 5123}, {'title': 'Get cabs now with GoJekFlash', 'company': 'GoJek', 'views': 62353}]


### Question 7

After having created a list of videos stored inside of `video_ads_list`, we want to finalise these videos and ensure that no modifications can be done to the list. We want to pass the data to another data analyst, and prevent future newbies from altering the list of video ads.

Based on your understanding, you know that tuples are able to store immutable data. This means that you cannot modify the data stored inside of tuples. As such, you intend to store a **`tuple` filled with the video ads** instead.

Your task is to add all the videos printed earlier into a tuple variable `video_ads` and to print out the resulting `video_ads` variable. In order to do this, you have no choice but to hard-code the answer.

**Example of how to proceed:**
```python
video_ads_list = (
    {"title": "Healthy Living", "company": "Health Promotion Board", "views": 65423}, 
    {"title": "Get a ride, anytime anywhere", "company": "GoJek", "views": 54323}
)
print(video_ads_list)
```

**Expected output:**
```python
    (
        {
            "title": "Healthy Living", 
            "company": "Health Promotion Board", 
            "views": 65423
        }, 
        {
            "title": "Get a ride, anytime anywhere", 
            "company": "GoJek", 
            "views": 54323
        }
        ...
    )
```

The reason why you have to hard-code this answer is primarily because tuples are immutable. Once you create the tuple, there's no way to add or remove from the tuple.

In [40]:
video_ads = tuple(video_ads_list)
print(video_ads)

({'title': 'Healthy Living', 'company': 'Health Promotion Board', 'views': 65423}, {'title': 'Get a ride, anytime anywhere', 'company': 'GoJek', 'views': 54323}, {'title': 'Send money to your friends with GrabPay', 'company': 'Grab', 'views': 654306}, {'title': 'GrabEat now delivers nationwide', 'company': 'Grab', 'views': 5123}, {'title': 'Get cabs now with GoJekFlash', 'company': 'GoJek', 'views': 62353})


In [55]:
video_ads_list = [
 {'title': 'Healthy Living', 'company': 'Health Promotion Board','views': 65423},
 {'title': 'Get a ride, anytime anywhere', 'company': 'GoJek', 'views': 54323},
 {'title': 'Send money to your friends with GrabPay', 'company': 'Grab', 'views': 654306},
 {'title': 'GrabEat now delivers nationwide', 'company': 'Grab', 'views': 5123},
 {'title': 'Get cabs now with GoJekFlash', 'company': 'GoJek', 'views': 62353}
]
video_ads = tuple(video_ads_list)
print(video_ads)

({'title': 'Healthy Living', 'company': 'Health Promotion Board', 'views': 65423}, {'title': 'Get a ride, anytime anywhere', 'company': 'GoJek', 'views': 54323}, {'title': 'Send money to your friends with GrabPay', 'company': 'Grab', 'views': 654306}, {'title': 'GrabEat now delivers nationwide', 'company': 'Grab', 'views': 5123}, {'title': 'Get cabs now with GoJekFlash', 'company': 'GoJek', 'views': 62353})


### Question 8
After having created a `tuple` variable `video_ads`, we want to find out how much we should be paid for each video (since YouTube charge for advertising). Let's create a payment model to calculate the the amount paid to us for each video 

**Here are the rules for the payment model:**

- If there are fewer than 10,000 views, each view is charged at \$0.82 each
- If there are fewer than 50,000 views but more than or equal to 10,000 views, each view is charged at \$0.68 each
- If there are more than or equal to 50,000 views, each view is charged at \$0.55 each

Make use of `if-elif-else` conditions to solve this problem, and get the final amount paid for each video.

**If you find yourself repeating the same logic many times, try copy-pasting your codes but changing the index.**

**Expected output:**
```
Healthy Living: $35982.65
Get a ride, anytime anywhere: $29877.65
Send money to your friends with GrabPay: $359868.30000000005
GrabEat now delivers nationwide: $4200.86
Get cabs now with GoJekFlash: $34294.15
```

In [57]:
healthy_living_check = video_ads_list[0]['views']
GoJek_check = video_ads_list[1]['views']
GrabPay_check = video_ads_list[2]['views']
GrabEat_check = video_ads_list[3]['views']
GoJekFlash_check = video_ads_list[4]['views']

if int(healthy_living_check) < 10000 :
    payment_healthyliving= 0.85* int(healthy_living_check)
elif int(healthy_living_check) > 10000 and int(healthy_living_check) <50000 :
    payment_healthyliving= 0.68* int(healthy_living_check)
else:
    payment_healthyliving= 0.55*int(healthy_living_check)

    
if int(GoJek_check) < 10000 :
    payment_GoJek= 0.85* int(GoJek_check)
elif int(GoJek_check) > 10000 and int(GoJek_check) <50000 :
    payment_GoJek= 0.68* int(GoJek_check)
else:
    payment_GoJek= 0.55*int(GoJek_check)

    
if int(GrabPay_check) < 10000 :
    payment_Grabpay= 0.85* int(GrabPay_check)
elif int(GrabPay_check) > 10000 and int(GrabPay_check) <50000 :
    payment_Grabpay= 0.68* int(GrabPay_check)
else:
    payment_Grabpay= 0.55*int(GrabPay_check)

    
if int(GrabEat_check) < 10000 :
    payment_GrabEat= 0.85* int(GrabEat_check)
elif int(GrabPay_check) > 10000 and int(GrabEat_check) <50000 :
    payment_GrabEat= 0.68* int(GrabEat_check)
else:
    payment_GrabEat= 0.55*int(GrabEat_check)

    
if int(GoJekFlash_check) < 10000 :
    payment_GoJekFlash= 0.85* int(GoJekFlash_check)
elif int(GrabPay_check) > 10000 and int(GoJekFlash_check) <50000 :
    payment_GoJekFlash= 0.68* int(GoJekFlash_check)
else:
    payment_GoJekFlash= 0.55*int(GoJekFlash_check)
                                        
print('Healthy Living: $'+ str(payment_healthyliving))
print('Get a ride, anytime anywhere: $'+ str(payment_GoJek))
print('Send money to your friends with GrabPay: $'+ str(payment_Grabpay))
print('GrabEat now delivers nationwide: $'+ str(payment_GrabEat))
print('Get cabs now with GoJekFlash: $' + str(payment_GoJekFlash))


Healthy Living: $35982.65
Get a ride, anytime anywhere: $29877.65
Send money to your friends with GrabPay: $359868.30000000005
GrabEat now delivers nationwide: $4354.55
Get cabs now with GoJekFlash: $34294.15


## Debugging
##### YOUTUBE ENGAGEMENT RATE
One of the common metrics used to evaluate YouTube channel success is the engagement rate (formula given below). 
<div class="alert alert-block alert-info"><center>engagement_rate = video_comments/video_views
 </center></div>

### Question 9
Another newbie to programming wrote the following piece of code to calculate the engagement rate of all videos in the database. However, her codes were met with syntax, logic bugs and exceptions. 

**Expected output**: 

    Total engagement rate is: 0.05202821869488536
    
Debug the following code for her.

In [1]:
all_videos = [
    {
        'title':'Kitchen Nightmares',
        'views': 45000,
        'comments': 2300 
    },
    {
        'title':'Overcooked Nightmares',
        'views': 65000,
        'comments': 3400
    },
    {
        'title':'Cooking Mama',
        'views': 3400,      
        'comments': 200
    }
]

all_views = all_videos[0]['views'] + all_videos[1]['views'] + all_videos[2]['views']
all_comments = all_videos[0]['comments'] + all_videos[1]['comments'] + all_videos[2]['comments']

print("Total engagement rate is " + str(all_comments/all_views)) 

Total engagement rate is 0.05202821869488536


### Question 10
Another newbie to programming wrote the following piece of code to check if one video has higher views than the other. However, him codes were met with syntax, logic bugs and exceptions. 

**Expected output**: 


    pompen has more views than purple rain

Debug the following code for him.

In [2]:
videos = { 
    'purple rain' : 7800 ,
    'pompen' : '12000'
}

purple_rain_views = videos['purple rain']
pompen_views = videos['pompen']
    
if purple_rain_views > int(pompen_views):
    print('purple rain has more views than pompen') 
else: 
    print('pompen has more views than purple rain')

pompen has more views than purple rain


## Additional Consolidation Questions (Optional)

<p>The following are additional questions that serves to strengthen your understanding in handling data from nested collections. The following collection structure are some of the common ways which people use to store their data for processing later on. </p>


### Q1 
<font color='red'><b>Run this cell first to get the `linked_data`</b></font>

In [14]:
linked_data = [
    ['Rick Jones', 'Software Engineer', 909802],
    ['Marissa Meyer', 'COO', 9320809],
    ['Avril Ting', 'MD', 932846]
]

##### Q1a
Extract Marissa's salary and print her name + salary

**Expected output**: 
    
    Marissa Meyer has a salary of $ 9320809

In [5]:
#Type your code below
print('Marissa Meyer has a salary of $ ' + str(linked_data[1][2]))

Marissa Meyer has a salary of $ 9320809


##### Q1b
Change Marissa's salary in linked_data to 78973930 & print out her data

**Expected output**: 

    
    ['Marissa Meyer', 'COO', 78973930]

In [15]:
#Type your code below
linked_data[1][2] = 78973930
print(linked_data[1])

['Marissa Meyer', 'COO', 78973930]


##### Q1c
Replace Avril Ting's entire data with the following ['Avril Tan', 'None', 0] & print `linked_data`

**Expected output**: 

    [
        ['Rick Jones', 'Software Engineer', 909802],
        ['Marissa Meyer', 'COO', 78973930],
        ['Avril Tan', 'None', 0]
    ]
    

In [16]:
#Type your code below
linked_data[2] = ['Avril Tan','None', 0] 
print(linked_data)

[['Rick Jones', 'Software Engineer', 909802], ['Marissa Meyer', 'COO', 78973930], ['Avril Tan', 'None', 0]]


##### Q1d
Add age data using the index method & print the `linked_data`. Age of the three person respectively: 20, 45, 55

Hint: Remember the_list[0] = 1000?

**Expected output**: 

    [
        ['Rick Jones', 'Software Engineer', 909802, 20],
        ['Marissa Meyer', 'COO', 78973930, 45],
        ['Avril Tan', 'None', 0, 55]
    ]
    

In [36]:
#Type your code below
linked_data[0].append(20)
linked_data[1].append(45)
linked_data[2].append(55)
print(linked_data)


[['Rick Jones', 'Software Engineer', 909802, 20, 20, 20], ['Marissa Meyer', 'COO', 78973930, 45], ['Avril Tan', 'None', 0, 55]]


### Q2
<font color='red'><b>Run this cell first to get the `linked_data`</b></font>

In [37]:
linked_data = [{'Name':'Rick Jones', 'Job':'Software Engineer', 'Salary':909802},
               {'Name':'Marissa Meyer', 'Job':'COO', 'Salary':9320809},
               {'Name':'Avril Ting', 'Job':'MD', 'Salary':932846}]

##### Q2a
Extract Marissa's salary and print her name + salary

**Expected output**: 
    
    Marissa Meyer has a salary of $ 9320809

In [41]:
#Type your code below
Marissa_salary = linked_data[1]['Salary']
print('Marissa Meyer has a salary of $ '+ str(Marissa_salary))

Marissa Meyer has a salary of $ 9320809


##### Q2b
Change Marissa's salary in linked_data to 78973930 & print out her data

**Expected output**: 
    
    { 
        'Name':'Marissa Meyer', 
        'Job':'COO', 
        'Salary':78973930
    }

In [42]:
#Type your code below
linked_data[1]['Salary'] = 78973930
print(linked_data[1])

{'Name': 'Marissa Meyer', 'Job': 'COO', 'Salary': 78973930}


##### Q2c
Replace Avril Ting's entire data with the following `{'Name':'Avril Tan', 'Job':'None', 'Salary':0}` & print `linked_data`

**Expected output**: 

    [
        {
            'Name':'Rick Jones', 
            'Job':'Software Engineer', 
            'Salary':909802
        },
        {
            'Name':'Marissa Meyer', 
            'Job':'COO', 
            'Salary':78973930
        },
        {
            'Name':'Avril Tan', 
            'Job':'None', 
            'Salary':0
        }
    ]
    

In [44]:
#Type your code below
linked_data[2]= {'Name':'Avril Tan', 'Job':'None', 'Salary':0}
print(linked_data)

[{'Name': 'Rick Jones', 'Job': 'Software Engineer', 'Salary': 909802}, {'Name': 'Marissa Meyer', 'Job': 'COO', 'Salary': 78973930}, {'Name': 'Avril Tan', 'Job': 'None', 'Salary': 0}]


##### Q2d
Add age data using the index method & print the `linked_data`. Age of the three person respectively: 20, 45, 55

Hint: Remember dict['key'] = 1000?

Expected output:

    [
        {
            'Name':'Rick Jones', 
            'Job':'Software Engineer', 
            'Salary':909802, 
            'age':20
        },
        {
            'Name':'Marissa Meyer', 
            'Job':'COO', 
            'Salary':78973930, 
            'age':45
        },
        {
            'Name':'Avril Tan', 
            'Job':'None', 
            'Salary':0, 
            'age':55
        }
    ]
    

In [50]:
#Type your code below
linked_data[0]['age'] = 20
linked_data[1]['age'] = 45
linked_data[2]['age'] = 55
print(linked_data)

[{'Name': 'Rick Jones', 'Job': 'Software Engineer', 'Salary': 909802, 'age': 20}, {'Name': 'Marissa Meyer', 'Job': 'COO', 'Salary': 78973930, 'age': 45}, {'Name': 'Avril Tan', 'Job': 'None', 'Salary': 0, 'age': 55}]


### Q3
<font color='red'><b>Run this cell first to get the `Department_Employee_data`</b></font>

In [51]:
Department_Employee_data= [{'Purchase': ['John', 'Avery', 'Obama'], 'Sales': ['Orea', 'Stark']},
                           {'Purchase': [2000, 4000, 10000], 'Sales': [2344, 32442]}]

#### Q3a
Extract Orea's salary and print her name + salary

**Expected output**: 
    
    Orea has a salary of $ 2344

In [53]:
#Type your code below
salary = Department_Employee_data[1]['Sales'][0]
print('Orea has  a salary of $ '+ str(salary))

Orea has  a salary of $ 2344


#### Q3b
Change Orea's salary to 2398 and print the entire Sales department's salary

**Expected output**: 
    
    [2398, 32442]

In [54]:
#Type your code below
Department_Employee_data[1]['Sales'][0] = 2398
print(Department_Employee_data[1]['Sales'])

[2398, 32442]
